#!/bin/sh

alias ls="ls --color=auto"
alias ll="ls -l"
alias f="ranger"
alias nv="nvim"
alias w="nvim -u $NVIM_CONFIG_DIR/writing.lua"
alias lg="lazygit"
alias gs="git status"
alias gl="git log"
alias gcm="git commit -m "
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias nvimc="nvim -c 'cd $NVIM_CONFIG_DIR' $NVIM_CONFIG_DIR/init.lua"
alias mpv="mpv --no-keepaspect-window --hwdec=auto"
